[package]
name = "workday_sftp_rest_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-stream = "0.3.6"
axum = { version = "0.8.4", features = ["http2", "macros", "multipart", "ws"] }
axum-auth = "0.8.1"
axum-extra = "0.10.1"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
axum-streams = "0.21.0"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.0-rc.1", features = ["derive"] }
csv = "1.1"
futures = "0.3"
glob = "0.3"
hyper = { version = "1.6.0", features = ["full"] }
lettre = { version = "0.10.2", features = ["tracing", "serde", "rustls", "tokio1", "tokio1-rustls-tls", "serde_json", "smtp-transport", "builder"], default-features = false }
once_cell = "1.17.1"
oracle = { version = "0.5.6", features = ["chrono"] }
r2d2-oracle = { version = "0.5.0", features = ["chrono"] }
regex = "1.7.1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
sha2 = "0.10.6"
suppaftp = "4.7.0"
tokio = { version = "1.46.1", features = ["full"] }
toml = { version = "0.7.2", features = ["preserve_order"] }
tower = "0.5.2"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["json", "env-filter", "registry"] }
url = { version = "2.3.1", features = ["serde"] }
